# Name(s)
Ishaan Jain

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

Is Jupyter's kernel related to a kernel in the context of operating systems?

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [1]:
# YOUR SOLUTION HERE
import numpy as np
a = np.full((6, 4), 2, int)
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [2]:
# YOUR SOLUTION HERE
b = np.full((6,4), 1, int)
np.fill_diagonal(b, 3)
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

In [3]:
# YOUR SOLUTION HERE
print(a*b)
# print(np.dot(a,b))
# a*b works because element-wise multiplication requires the two matrices to have the same dimensions.
# np.dot(a,b) does not work because it requires the number of columns of the first matrix to equal the number of rows of the second matrix.

[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 4

In [4]:
# YOUR SOLUTION HERE
print(np.dot(a.transpose(),b))
print(np.dot(a,b.transpose()))
# The results are different shapes because the shape of the output matrix depends on the number of rows of the first matrix and number
# of columns of the second matrix.

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]


## Exercise 5

In [11]:
# YOUR SOLUTION HERE
def give_greeting():
    print('hi')
give_greeting()

hi


## Exercise 6

In [12]:
# YOUR SOLUTION HERE
def random_arrays():
    for i in range(0,3):
        a = np.random.randint(11,size=(5,5))
        print(a)
        print('sum:', np.sum(a))
        print('mean:', np.mean(a))
random_arrays()

[[3 5 6 3 2]
 [4 9 8 9 5]
 [4 8 9 7 7]
 [4 9 2 9 0]
 [0 5 4 3 3]]
sum: 128
mean: 5.12
[[ 9  7  1  3  8]
 [ 9  6  2  8  3]
 [10 10  5  0  6]
 [ 2  1  1  9  6]
 [ 8  1  4  1  1]]
sum: 121
mean: 4.84
[[10  0  8  4  9]
 [10  0  0  7  1]
 [ 3  0  5  0  6]
 [ 6  0  8  3  5]
 [ 5  1 10  3  4]]
sum: 108
mean: 4.32


## Exercise 7

In [54]:
# YOUR SOLUTION HERE
def count_ones_v1(m):
    num_ones = 0
    for elem in np.ndarray.flatten(m):
        if elem == 1:
            num_ones += 1
    print(num_ones)
def count_ones_v2(m):
    num_ones = len(np.where(m==1)[0])
    print(num_ones)
rand_matrix = np.random.randint(11,size=(3,3))
count_ones_v1(rand_matrix)
count_ones_v2(rand_matrix)

0
0


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE